DROP TABLE energy;

create external table energy (
    genmix_biogas_gen_MW double, 
	genmix_biogas_fuel string, 
	genmix_nuclear_fuel string, 
	genmix_thermal_fuel string, 
	market string, 
	genmix_coal_fuel string, 
	genmix_biomass_gen_MW double, 
	genmix_solar_gen_MW double,
	genmix_nonwind_gen_MW double, 
	genmix_renewable_gen_MW double, 
	genmix_wind_gen_MW double, 
	genmix_nuclear_gen_MW double, 
	genmix_solar_fuel string, 
	ba string, 
	genmix_thermal_gen_MW double, 
	timestamp string, 
	genmix_coal_gen_MW double, 
	genmix_refuse_fuel string, 
	genmix_other_fuel string, 
	carbon double, 
	freq string, 
	genmix_refuse_gen_MW double, 
	genmix_other_gen_MW double, 
	genmix_renewable_fuel string, 
	genmix_wind_fuel string, 
	genmix_nonwind_fuel string, 
	genmix_natgas_gen_MW double, 
	url string, 
	created_at string, 
	genmix_hydro_fuel string, 
	genmix_natgas_fuel string, 
	genmix_hydro_gen_MW double, 
	genmix_biomass_fuel string
  )
row format serde 'org.openx.data.jsonserde.JsonSerDe'
with serdeproperties (
'paths'= 'genmix_biogas_gen_MW,
	genmix_biogas_fuel,
	genmix_nuclear_fuel,
	genmix_thermal_fuel,
	market,
	genmix_coal_fuel,
	genmix_biomass_gen_MW,
	genmix_solar_gen_MW,
	genmix_nonwind_gen_MW,
	genmix_renewable_gen_MW,
	genmix_wind_gen_MW,
	genmix_nuclear_gen_MW,
	genmix_solar_fuel,
	ba,
	genmix_thermal_gen_MW,
	timestamp,
	genmix_coal_gen_MW,
	genmix_refuse_fuel,
	genmix_other_fuel,
	carbon,
	freq,
	genmix_refuse_gen_MW,
	genmix_other_gen_MW,
	genmix_renewable_fuel,
	genmix_wind_fuel,
	genmix_nonwind_fuel,
	genmix_natgas_gen_MW,
	url,
	created_at,
	genmix_hydro_fuel,
	genmix_natgas_fuel,
	genmix_hydro_gen_MW,
	genmix_biomass_fuel'
)
stored as textfile
location '/user/w205/W205FinalProject';
